import React from 'react';
import type { SalesMetric, FunnelStage, LeadSource, Campaign, Activity, RecentActivityItem, WidgetKey, WidgetData } from './types';
import { DollarSign, Users, Target, BarChart2 } from './components/Icons';

export const SALES_METRICS_DATA: SalesMetric[] = [
  { label: 'Total Revenue', value: '$405,231', change: '+12.5%', changeType: 'increase', icon: DollarSign },
  { label: 'New Clients', value: '316', change: '+8.2%', changeType: 'increase', icon: Users },
  { label: 'Deals Closed', value: '1,209', change: '-2.1%', changeType: 'decrease', icon: Target },
  { label: 'Conversion Rate', value: '25.4%', change: '+1.8%', changeType: 'increase', icon: BarChart2 },
];

export const FUNNEL_DATA: FunnelStage[] = [
  { name: 'Visitors', value: 10000, fill: '#8884d8' },
  { name: 'Leads', value: 4567, fill: '#83a6ed' },
  { name: 'Qualified Leads', value: 1567, fill: '#8dd1e1' },
  { name: 'Proposals', value: 900, fill: '#82ca9d' },
  { name: 'Deals Won', value: 316, fill: '#a4de6c' },
];

export const LEAD_SOURCE_DATA: LeadSource[] = [
  { name: 'Organic Search', value: 400, fill: '#0088FE' },
  { name: 'Social Media', value: 300, fill: '#00C49F' },
  { name: 'Referrals', value: 300, fill: '#FFBB28' },
  { name: 'Paid Ads', value: 200, fill: '#FF8042' },
];

export const CAMPAIGN_DATA: Campaign[] = [
  { name: 'Q2 Promo', cost: 5000, revenue: 15000, roi: 200 },
  { name: 'Summer Sale', cost: 8000, revenue: 25000, roi: 212 },
  { name: 'Webinar Series', cost: 3000, revenue: 12000, roi: 300 },
  { name: 'Email Blast', cost: 1500, revenue: 7500, roi: 400 },
  { name: 'Social Ads', cost: 12000, revenue: 30000, roi: 150 },
];

export const ACTIVITY_DATA: Activity[] = Array.from({ length: 98 }, (_, i) => ({
  day: `Day ${i + 1}`,
  value: Math.floor(Math.random() * 50) + Math.floor(Math.random() * (i / 1.5)),
}));

export const RECENT_ACTIVITY_DATA: RecentActivityItem[] = [
  { id: 1, type: 'deal', description: 'closed a $5,200 deal', person: 'John Doe', time: '5m ago' },
  { id: 2, type: 'call', description: 'had a discovery call with', person: 'Jane Smith', time: '25m ago' },
  { id: 3, type: 'email', description: 'sent a follow-up email to', person: 'ACME Corp', time: '1h ago' },
  { id: 4, type: 'meeting', description: 'scheduled a demo for', person: 'Tech Solutions', time: '3h ago' },
  { id: 5, type: 'deal', description: 'updated deal stage for', person: 'Global Inc.', time: '5h ago' },
];

export const WIDGETS_DATA: Record<WidgetKey, WidgetData> = {
  salesMetrics: { title: 'Sales Snapshot', description: 'Key performance indicators for the current quarter.', gridSpan: 4 },
  aiSummary: { title: 'AI-Powered Insights', description: 'Weekly summary generated by Gemini.', gridSpan: 4 },
  conversionFunnel: { title: 'Conversion Funnel', description: 'From initial visit to closed deal.', gridSpan: 2 },
  leadSources: { title: 'Lead Sources', description: 'Where your new leads are coming from.', gridSpan: 2 },
  campaignPerformance: { title: 'Campaign Performance', description: 'ROI and effectiveness of marketing campaigns.', gridSpan: 4 },
  activityHeatmap: { title: 'Team Activity', description: 'Activity levels over the last 14 weeks.', gridSpan: 3 },
  recentActivity: { title: 'Recent Activity', description: 'A live feed of team interactions.', gridSpan: 1 },
};